#!/usr/bin/env python

# Run this before you deploy it on replicate
import os
import sys
import torch
from diffusers import DiffusionPipeline, AutoencoderKL

# append project directory to path so predict.py can be imported
sys.path.append('.')
from predict import MODEL_NAME, SDXL_REFINER, SDXL_MODEL_CACHE, REFINER_MODEL_CACHE

# Make cache folders
if not os.path.exists(SDXL_MODEL_CACHE):
    os.makedirs(SDXL_MODEL_CACHE)

if not os.path.exists(REFINER_MODEL_CACHE):
    os.makedirs(REFINER_MODEL_CACHE)


# SD-XL-Base-1.0 refiner
pipe = DiffusionPipeline.from_pretrained(
    SDXL_REFINER,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
)
pipe.save_pretrained(REFINER_MODEL_CACHE, safe_serialization=True)


# Download SDXL-VAE-FP16-Fix
better_vae = AutoencoderKL.from_pretrained(
    "madebyollin/sdxl-vae-fp16-fix",
    torch_dtype=torch.float16,
)

# SD-XL-Base-1.0
pipe = DiffusionPipeline.from_pretrained(
    MODEL_NAME,
    vae=better_vae,
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16",
)
pipe.save_pretrained(SDXL_MODEL_CACHE, safe_serialization=True)
